services:
    nginx:
        image: nginx:alpine
        ports:
            - "8078:80"
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - .:/var/www/html
        depends_on:
            - php-fpm
        networks:
            - app-network

    php-fpm:
        build:
            context: .
            dockerfile: docker/php/Dockerfile.php
        volumes:
            - .:/var/www/html
        environment:
            PHP_IDE_CONFIG: "serverName=test_mx"
        extra_hosts:
            - host.docker.internal:host-gateway
        networks:
            - app-network
        depends_on:
            - mariadb
            - postgres

    mariadb:
        image: mariadb:10.8
        ports:
            - ${DOCKER_MYSQL_PORT}:3306
        environment:
            MARIADB_ROOT_PASSWORD: ${MYSQL_DB_ROOT_PASS} # Set the root password
            MARIADB_USER: ${MYSQL_DB_NAME} # Create a new user
            MARIADB_PASSWORD: ${MYSQL_DB_PASS} # Set password for the new user
            MARIADB_DATABASE: ${MYSQL_DB_NAME} # Create a new database
        volumes:
            - mariadb_data:/var/lib/mysql # Mount a named volume for data persistence
        restart: always # Ensure the container restarts automatically
        networks:
            - app-network

    postgres:
        image: 'postgres:12'
        volumes:
            - postgres_data:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: ${POSTGRES_DB_NAME}
            POSTGRES_USER: ${POSTGRES_DB_USER}
            POSTGRES_PASSWORD: ${POSTGRES_DB_PASS}
        ports:
            - ${DOCKER_POSTGRES_PORT}:5432
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    mariadb_data:
    postgres_data: